using System.Text;
using WinChime.Core.Model;
using WinChime.Core.Sounds;
using WinChime.SoundPackGenerator;

// Builds packs/WinChime Chime.winchimepack.
//
// Every sound is synthesised rather than sourced, so the whole pack is reproducible from
// this file and carries no third-party licensing. They are built from one pentatonic set
// (C-D-E-G-A), which is why any two of them played together still sound intentional.

const double C4 = 261.63, E4 = 329.63, G4 = 392.00, A4 = 440.00;
const double C5 = 523.25, D5 = 587.33, E5 = 659.25, G5 = 783.99, A5 = 880.00, C6 = 1046.50;

var root = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
var mediaFolder = Path.Combine(Path.GetTempPath(), "winchime-starter-pack");

if (Directory.Exists(mediaFolder)) Directory.Delete(mediaFolder, recursive: true);
Directory.CreateDirectory(mediaFolder);

// --- the sounds -------------------------------------------------------------------------

var sounds = new Dictionary<string, Synth>
{
    // Gentle rising third. The most frequently heard sound in the set, so it is the
    // shortest and least insistent.
    ["notification"] = new Synth(0.90)
        .Note(E5, 0.00, decay: 3.2)
        .Note(G5, 0.13, decay: 3.2, amplitude: 0.85),

    // One note, quick. A default beep that outstays its welcome is genuinely irritating.
    ["beep"] = new Synth(0.42)
        .Note(G5, 0.00, decay: 7.0),

    // Falling, low and round. Soft partials because shimmer on an error sound feels wrong.
    ["critical"] = new Synth(1.25)
        .Note(A4, 0.00, decay: 2.1, ratios: Synth.SoftRatios, amps: Synth.SoftAmps)
        .Note(E4, 0.17, decay: 2.0, amplitude: 0.9, ratios: Synth.SoftRatios, amps: Synth.SoftAmps),

    // A dyad rather than a sequence: it arrives all at once, which suits an interruption.
    ["exclamation"] = new Synth(0.85)
        .Note(C5, 0.00, decay: 3.6)
        .Note(E5, 0.00, decay: 3.6, amplitude: 0.7),

    // Rising fourth, left hanging. Reads as a question without needing to be clever.
    ["question"] = new Synth(0.95)
        .Note(E5, 0.00, decay: 3.0)
        .Note(A5, 0.14, decay: 2.8, amplitude: 0.85),

    ["connect"] = new Synth(0.70)
        .Note(C5, 0.00, decay: 5.5)
        .Note(G5, 0.11, decay: 5.0, amplitude: 0.9),

    // Deliberately the exact inverse of connect, so the pair is unmistakable.
    ["disconnect"] = new Synth(0.70)
        .Note(G5, 0.00, decay: 5.5)
        .Note(C5, 0.11, decay: 5.0, amplitude: 0.9),

    // Noise rather than pitch: emptying the bin is movement, not an event to announce.
    ["recycle"] = new Synth(0.55)
        .Swish(0.00, 0.45),

    // The longest and warmest, since it plays once per session rather than constantly.
    ["logon"] = new Synth(1.70)
        .Note(C5, 0.00, decay: 2.0)
        .Note(E5, 0.15, decay: 2.0, amplitude: 0.9)
        .Note(G5, 0.30, decay: 1.8, amplitude: 0.85)
        .Note(C6, 0.45, decay: 1.6, amplitude: 0.6),

    ["logoff"] = new Synth(1.30)
        .Note(G4, 0.00, decay: 2.4, ratios: Synth.SoftRatios, amps: Synth.SoftAmps)
        .Note(D5, 0.14, decay: 2.2, amplitude: 0.8, ratios: Synth.SoftRatios, amps: Synth.SoftAmps)
        .Note(C4, 0.28, decay: 2.0, amplitude: 0.7, ratios: Synth.SoftRatios, amps: Synth.SoftAmps),
};

var paths = new Dictionary<string, string>();

foreach (var (name, synth) in sounds)
{
    var path = Path.Combine(mediaFolder, $"{name}.wav");
    WriteMonoPcmWav(path, synth.Render());
    paths[name] = path;

    var info = WaveFile.Inspect(path);
    Console.WriteLine($"  {name,-14} {info.Summary}");

    if (!info.IsPlayableByWindows) throw new InvalidOperationException($"{name} is not playable by Windows.");
}

// --- the mapping ------------------------------------------------------------------------

// Several events share a file on purpose: it keeps the set coherent, and it exercises the
// deduplication in SoundPackService, which stores a shared file once.
var scheme = new SchemeExport
{
    Name = "WinChime Chime",
    Author = "Generated by tools/SoundPackGenerator",
    Description = "A calm synthesised set built from a single pentatonic scale.",
    Assignments =
    {
        [@".Default\Notification.Default"] = paths["notification"],
        [@".Default\SystemNotification"] = paths["notification"],
        [@".Default\SystemAsterisk"] = paths["notification"],
        [@".Default\.Default"] = paths["beep"],
        [@".Default\SystemHand"] = paths["critical"],
        [@".Default\SystemExclamation"] = paths["exclamation"],
        [@".Default\SystemQuestion"] = paths["question"],
        [@".Default\DeviceConnect"] = paths["connect"],
        [@".Default\DeviceDisconnect"] = paths["disconnect"],
        [@".Default\DeviceFail"] = paths["critical"],
        [@".Default\LowBatteryAlarm"] = paths["question"],
        [@".Default\MailBeep"] = paths["notification"],
        [@".Default\WindowsLogon"] = paths["logon"],
        [@".Default\WindowsLogoff"] = paths["logoff"],
        [@"Explorer\EmptyRecycleBin"] = paths["recycle"],
    },
};

var destination = Path.Combine(root, "packs", "WinChime Chime.winchimepack");
Directory.CreateDirectory(Path.GetDirectoryName(destination)!);

var result = SoundPackService.Create(destination, scheme);

Console.WriteLine();
foreach (var warning in result.Warnings) Console.WriteLine($"  warning: {warning}");
Console.WriteLine(result.Message);
Console.WriteLine($"  -> {destination}");

Directory.Delete(mediaFolder, recursive: true);

if (!result.Success) Environment.Exit(1);

/// <summary>
/// Writes 16-bit mono PCM by hand rather than pulling in a library. Mono halves the file
/// size for no audible loss on a two-second chime, and these are committed to the repo.
/// </summary>
static void WriteMonoPcmWav(string path, short[] samples)
{
    const int channels = 1;
    const int bitsPerSample = 16;

    var byteRate = Synth.SampleRate * channels * bitsPerSample / 8;
    var blockAlign = channels * bitsPerSample / 8;
    var dataBytes = samples.Length * 2;

    using var stream = File.Create(path);
    using var writer = new BinaryWriter(stream, Encoding.ASCII);

    writer.Write(Encoding.ASCII.GetBytes("RIFF"));
    writer.Write(36 + dataBytes);
    writer.Write(Encoding.ASCII.GetBytes("WAVE"));

    writer.Write(Encoding.ASCII.GetBytes("fmt "));
    writer.Write(16);
    writer.Write((short)1);              // PCM
    writer.Write((short)channels);
    writer.Write(Synth.SampleRate);
    writer.Write(byteRate);
    writer.Write((short)blockAlign);
    writer.Write((short)bitsPerSample);

    writer.Write(Encoding.ASCII.GetBytes("data"));
    writer.Write(dataBytes);

    foreach (var sample in samples) writer.Write(sample);
}
